language: java
jdk: openjdk8

services:
  - mysql

branches:
  only:
    - master

notifications:
  email: false

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n"