language: java
jdk: openjdk8

services:
  - mysql

branches:
  only:
    - master

notifications:
  email: false

before_install:
  - sudo mysql -e "use mysql; update user set password=PASSWORD('pass') where User='root';FLUSH PRIVILEGES;"
  - sudo service mysql restart

before_script:
  - sudo mysql -e 'CREATE DATABASE company;'