language: java
jdk: openjdk8

services:
  - mysql

branches:
  only:
    - master

notifications:
  email: false

  before_script:
    - mysql -e 'create database company'
    - mysql -u root --password="pass"
